### PR TITLE
[TJS-22] Use a simpler regex to detect line endings to split XML files by line

### PR DESCRIPTION
**Pull request by bobness**
TODO
- [x] Implement better `position()` function in xmldom, fork from github, create PR
- [ ] Change taniumjs package.json to use this package instead of the main one - change its name? something else?

### CODE REVIEW

**Comment by harlev** [comment]
Do we have a good way to test this?

**Comment by smithgcovert** [comment]
The jira TJS-22 includes a zip file with an xml that fails with the previous code.  Assuming this works fine with that test file, this looks good to me.

**Comment by bobness** [comment]
Yep, it works with the example `soap.xml`, and I also did development based on my own simpler file:
```
<p>
<span>hi there</span>
</p>
```

**Comment by bobness** [comment]
[xmldom_parse_failure.zip](https://github.com/tanium/xmldom/files/2106914/xmldom_parse_failure.zip)

**Pull request merged**
